Import('sample_env')

progs = [
    sample_env.Program('SecureClientECDHE', ['SecureClientECDHE.c']),
    sample_env.Program('SecureServiceECDHE', ['SecureServiceECDHE.c'])
]
sample_env.Install("#dist/bin", progs)
