# Copyright AllSeen Alliance. All rights reserved.
#
# SDPX-License-Identifier: ISC

Import('sample_env')

progs = [
    sample_env.Program('net_bus', ['NetworkAndBus.c'])
]
sample_env.Install("#dist/bin", progs)
