# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

#

Import('env')

# Add/remove projects from build

# Only build the following samples for the TARG operating system.
# The samples/examples for target platforms are handled by
# the target specific directory (viz. target/arduino).
if env['TARG'] in [ 'win32', 'linux', 'darwin' ]:
    env.SConscript(['basic/SConscript'])
    env.SConscript(['secure/SConscript'])
    env.SConscript(['network/SConscript'])
