# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


Import('env')

env.Program('basic_service', ['basic_service.c'] + env['aj_obj'])
env.Program('basic_client', ['basic_client.c'] + env['aj_obj'])
env.Program('signal_service', ['signal_service.c'] + env['aj_obj'])
env.Program('nameChange_client', ['nameChange_client.c'] + env['aj_obj'])
env.Program('signalConsumer_client', ['signalConsumer_client.c'] + env['aj_obj'])
env.Program('eventaction_service', ['eventaction_service.c'] + env['aj_obj'])