Import('sample_env')

progs = [
    sample_env.Program('basic_service', ['basic_service.c']),
    sample_env.Program('basic_client', ['basic_client.c']),
    sample_env.Program('signal_service', ['signal_service.c']),
    sample_env.Program('nameChange_client', ['nameChange_client.c']),
    sample_env.Program('signalConsumer_client', ['signalConsumer_client.c']),
    sample_env.Program('eventaction_service', ['eventaction_service.c'])
]
sample_env.Install("#dist/bin", progs)
